name: build-pr

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.19.x, 1.20.x]

    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: setup go environment
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      
      - name: create go.mod
        run: |
          # Fix for "cannot find main module" issue
          go mod init github.com/opencontainers/runtime-spec

          go get -d ./schema/...

      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: --verbose

      - name: run tests
        run: |
          set -x
          make install.tools

          make .govet

          make .gitvalidation
          make docs
          make -C schema test
